from pydantic import BaseModel, Field
from typing import List

class BiasCorrection(BaseModel):
    """An individual instance where loaded language or cultural bias was sanitized."""
    agent_id: str = Field(..., description="The ID of the evaluation agent where bias was caught")
    original_phrase: str = Field(..., description="The flagged phrase or demographic leak text")
    corrected_phrase: str = Field(..., description="The safe, objective, neutralized wording replacement")
    rationale: str = Field(..., description="The reason why this phrase breached structural standards")

class BiasLog(BaseModel):
    """Audit ledger generated by the Bias Detection Agent to evaluate compliance."""
    bias_detected: bool = Field(..., description="Flag indicating if any loaded or unfair framing was intercepted")
    corrections: List[BiasCorrection] = Field(default_factory=list, description="Ordered list of redacted items")